/*
 * This file is generated by jOOQ.
 */
package org.example.dm;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.example.dm.tables.TableTestTable;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbTest extends SchemaImpl {

    private static final long serialVersionUID = -1810506370;

    /**
     * The reference instance of <code>DB_TEST</code>
     */
    public static final DbTest DB_TEST = new DbTest();

    /**
     * The table <code>DB_TEST.TABLE_TEST</code>.
     */
    public final TableTestTable TABLE_TEST = TableTestTable.TABLE_TEST;

    /**
     * No further instances allowed
     */
    private DbTest() {
        super("DB_TEST", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TableTestTable.TABLE_TEST);
    }
}
