/*
 * This file is generated by jOOQ.
 */
package org.example.dm;


import javax.annotation.Generated;

import org.example.dm.tables.TableTestTable;
import org.example.dm.tables.records.TableTestRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>DB_TEST</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TableTestRecord> PK_TABLE_TEST = UniqueKeys0.PK_TABLE_TEST;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TableTestRecord> PK_TABLE_TEST = Internal.createUniqueKey(TableTestTable.TABLE_TEST, "PK_TABLE_TEST", TableTestTable.TABLE_TEST.ID);
    }
}
