/*
 * This file is generated by jOOQ.
 */
package org.example.dm;


import javax.annotation.Generated;

import org.example.dm.tables.TableTestTable;


/**
 * Convenience access to all tables in DB_TEST
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_TEST.TABLE_TEST</code>.
     */
    public static final TableTestTable TABLE_TEST = TableTestTable.TABLE_TEST;
}
